version: '3'
services:
  c_kollektiv_db:
    image: 'postgres:latest'
    container_name: c_kollektiv_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./.db-data/:/var/lib/postgresql/data/
    env_file:
      - ".env"
